apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: spring-app
  template:
    metadata:
      labels:
        name: spring-app
    spec:
      containers:
        - name: minikube
          image: harry997/minikube-spring-app
          ports:
            - containerPort: 9090
    