apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: spring-app
  template:
    metadata:
      labels:
        name: spring-app
    spec:
      containers:
        - name: minikube
          image: localhost:8083/spring-app:latest
          ports:
            - containerPort: 9090
      imagePullSecrets:
        - name: nexus-secret
    